---
- name: Deploy IPC cluster anchored to calibration net
  hosts: vm
  remote_user: ubuntu

  tasks:
    # - name: Install build dependencies
    #   become: yes
    #   become_user: root
    #   apt:
    #     update-cache: yes
    #     pkg:
    #       - build-essential
    #       - libssl-dev
    #       - mesa-opencl-icd
    #       - ocl-icd-opencl-dev
    #       - gcc
    #       - git
    #       - bzr
    #       - jq
    #       - pkg-config
    #       - curl
    #       - clang
    #       - hwloc
    #       - libhwloc-dev
    #       - wget
    #       - ca-certificates
    #       - gnupg

    - name: Check if rustc/cargo is installed
      # shell: source ~/.bashrc && command -v cargo
      shell: bash -ilc 'which cargo'
      register: cargo_exists
      ignore_errors: yes

    - name: Download rustc/cargo Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'

    - debug:
        var: cargo_exists

    - name: Install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y

    - name: Get current date in yyyy-mm-dd format
      command: date +%F
      register: current_date

    - name: Set ipc folder name as variable
      set_fact:
        ipc_folder_path: ~/ipc-{{ current_date.stdout }}

    - debug:
        var: ipc_folder_path

    # TODO(jie): The repo folder name should be changed to yyyy-mm-dd-hh-ss
    # - name: Checkout ipc repo
    #   git:
    #     repo: https://github.com/consensus-shipyard/ipc.git
    #     dest: ipc_folder_path

    - name: Build ipc-cli
      command: bash -ilc 'make build'
      args:
        chdir: "{{ ipc_folder_path }}/ipc"