[tasks.prometheus-pull]
script = "docker pull prom/prometheus"

[tasks.prometheus-run]
script = "docker run -p 9090:9090 -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus"

[tasks.default]
clear = true
script_runner = "@duckscript"
script = [
  '''
    echo
    echo Main tasks:
    echo - testnet: run 4-nodes testnet
    echo - testnet-down: stop the testnet
    echo - testnode: run a test node
    echo - testnode-down: stop the test node
    echo - info: Print the setup information
    echo
    echo Most tasks use these environment variables:
    echo - SUBNET_ID (default '${SUBNET_ID}'): the target IPC subnet
    echo
    echo Run 'cargo make -e SUBNET_ID=chain -e BALANCE=100 -e BASE_FEE=200 ... COMMAND' to populate the variables from CLI or
    echo Run 'cargo make --env-file=/PATH/.env COMMAND' to populate the variables from the file before running the command.
    echo
    echo Run 'cargo make --list-all-steps' for a complete list of available tasks.
    echo
''',
]
