[tasks.prometheus-pull]
script = "docker pull prom/prometheus"

[tasks.prometheus-run]
script = "docker run -p 9090:9090 -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus"

[tasks.default]
clear = true
script_runner = "@duckscript"
script = [
  '''
    echo
    echo How to use:
    echo
    echo Run 'cargo make prometheus-pull' to pull the latest Prometheus docker image.
    echo Run 'cargo make prometheus-run' to start Prometheus. You can then visit http://localhost:9090 for Prometheus web UI. Press Ctrl-C to stop running.
    echo
''',
]
