name: Mythril Test

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust this as needed for your project

      - name: Install dependencies
        run: cd contracts && npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: false

      - name: Install solc
        run: |
          sudo wget -O /usr/bin/solc https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux
          sudo chmod +x /usr/bin/solc

      - name: Install mythril
        run: |
          pip3 install mythril

      - name: Check GatewayManagerFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/gateway/GatewayManagerFacet.sol --solv 0.8.19

      - name: Check GatewayGetterFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/gateway/GatewayGetterFacet.sol --solv 0.8.19

      - name: Check GatewayMessengerFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/gateway/GatewayMessengerFacet.sol --solv 0.8.19

      - name: Check CheckpointingFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/gateway/router/CheckpointingFacet.sol --solv 0.8.19

      - name: Check TopDownFinalityFacade
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/gateway/router/TopDownFinalityFacet.sol --solv 0.8.19

      - name: Check XnetMessagingFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/gateway/router/XnetMessagingFacet.sol --solv 0.8.19

      - name: Check SubnetActorRewardFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/subnet/SubnetActorRewardFacet.sol --solv 0.8.19

      - name: Check SubnetActorGetterFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/subnet/SubnetActorGetterFacet.sol --solv 0.8.19

      - name: Check SubnetActorPauseFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/subnet/SubnetActorPauseFacet.sol --solv 0.8.19

      - name: Check SubnetActorManagerFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/subnet/SubnetActorManagerFacet.sol --solv 0.8.19
          

      - name: Check SubnetActorRegistry
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/subnetregistry/RegisterSubnetFacet.sol --solv 0.8.19

      - name: Check SubnetGetterFacet
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./src/subnetregistry/SubnetGetterFacet.sol --solv 0.8.19

