name: Mythril Test

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Adjust this as needed for your project

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install solc
        run: |
          sudo wget -O /usr/bin/solc https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux
          sudo chmod +x /usr/bin/solc

      - name: Install mythril
        run: |
          pip3 install mythril

      - name: Run mythril
        run: |
          cd contracts
          myth analyze --solc-json remappings.json ./test/invariants/handlers/GatewayActorFacade.sol --solv 0.8.19
